const std = @import("std");

const source_path = "../zigrep/src/regex/unicode_props_generated.zig";
const output_path = "src/unicode_slug_data.zig";
const declarations = [_][]const u8{
    "letter_ranges",
    "number_ranges",
    "whitespace_ranges",
    "simple_case_fold_mappings",
};

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const source = try std.Io.Dir.cwd().readFileAlloc(
        init.io,
        source_path,
        arena,
        .limited(2 * 1024 * 1024),
    );
    const file = try std.Io.Dir.cwd().createFile(init.io, output_path, .{ .truncate = true });
    defer file.close(init.io);

    var buffer: [4096]u8 = undefined;
    var writer = file.writer(init.io, &buffer);
    try writer.interface.writeAll(
        \\// Generated by tools/gen_unicode_slug_data.zig from zigrep's focused
        \\// Unicode tables. Do not edit this file directly.
        \\// Source data: Unicode 16.0.0 from the zg Unicode data set.
        \\// https://codeberg.org/atman/zg
        \\// License: docs/UNICODE_LICENSE.md
        \\
        \\pub const Range = struct {
        \\    start: u32,
        \\    end: u32,
        \\};
        \\
        \\pub const CaseFoldMapping = struct {
        \\    from: u32,
        \\    to: u32,
        \\};
        \\
    );
    try writer.interface.writeByte('\n');

    for (declarations, 0..) |name, index| {
        try writer.interface.writeAll(try declaration(source, name));
        try writer.interface.writeAll(if (index + 1 == declarations.len) "\n" else "\n\n");
    }
    try writer.interface.flush();
}

fn declaration(source: []const u8, name: []const u8) ![]const u8 {
    var prefix_buffer: [96]u8 = undefined;
    const prefix = try std.fmt.bufPrint(&prefix_buffer, "pub const {s} =", .{name});
    const start = std.mem.indexOf(u8, source, prefix) orelse return error.MissingDeclaration;
    const relative_end = std.mem.indexOf(u8, source[start..], "\n};") orelse
        return error.UnterminatedDeclaration;
    return source[start .. start + relative_end + "\n};".len];
}
