const std = @import("std");
const math = @import("math_typesetter");

pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len != 5) return fatal(
        init,
        "usage: generate-formula-logo FORMULA BACKGROUND FOREGROUND OUTPUT_SVG",
        .{},
    );

    const formula = stripInlineDelimiters(args[1]) orelse
        return fatal(init, "formula must contain non-empty inline math", .{});
    if (!isHexColor(args[2])) return fatal(init, "invalid background color '{s}'", .{args[2]});
    if (!isHexColor(args[3])) return fatal(init, "invalid foreground color '{s}'", .{args[3]});

    var rendered = math.renderMathMlAlloc(init.gpa, formula, .{}) catch |err| {
        return fatal(init, "cannot render formula: {s}", .{@errorName(err)});
    };
    defer rendered.deinit(init.gpa);
    const mathml = switch (rendered) {
        .output => |output| output,
        .diagnostic => |failure| return fatal(
            init,
            "formula is unsupported at bytes {d}..{d}: {s}",
            .{ failure.span.start, failure.span.end, @tagName(failure.code) },
        ),
    };

    var output = std.Io.Dir.cwd().createFile(init.io, args[4], .{ .truncate = true }) catch |err| {
        return fatal(init, "cannot create '{s}': {s}", .{ args[4], @errorName(err) });
    };
    defer output.close(init.io);
    var buffer: [4096]u8 = undefined;
    var file_writer = output.writer(init.io, &buffer);
    writeSvg(&file_writer.interface, mathml, args[2], args[3]) catch |err| {
        return fatal(init, "cannot write '{s}': {s}", .{ args[4], @errorName(err) });
    };
    file_writer.interface.flush() catch |err| {
        return fatal(init, "cannot flush '{s}': {s}", .{ args[4], @errorName(err) });
    };
}

fn stripInlineDelimiters(value: []const u8) ?[]const u8 {
    const trimmed = std.mem.trim(u8, value, " \t\r\n");
    const formula = if (trimmed.len >= 2 and trimmed[0] == '$' and trimmed[trimmed.len - 1] == '$')
        std.mem.trim(u8, trimmed[1 .. trimmed.len - 1], " \t\r\n")
    else
        trimmed;
    return if (formula.len == 0) null else formula;
}

fn isHexColor(value: []const u8) bool {
    if (value.len != 7 or value[0] != '#') return false;
    for (value[1..]) |byte| if (!std.ascii.isHex(byte)) return false;
    return true;
}

fn writeSvg(
    writer: *std.Io.Writer,
    mathml: []const u8,
    background: []const u8,
    foreground: []const u8,
) std.Io.Writer.Error!void {
    try writer.writeAll(
        \\<!-- Generated by ./build.sh update-logo; do not edit directly. -->
        \\<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 64 64">
        \\
    );
    try writer.print("  <rect width=\"64\" height=\"64\" rx=\"12\" fill=\"{s}\"/>\n", .{background});
    try writer.writeAll(
        \\  <foreignObject x="2" y="2" width="60" height="60">
        \\
    );
    try writer.print(
        "    <div xmlns=\"http://www.w3.org/1999/xhtml\" style=\"width:100%;height:100%;display:flex;align-items:center;justify-content:center;color:{s};font-size:42px;line-height:1\">\n",
        .{foreground},
    );
    try writer.writeAll("      ");
    try writeNamespacedMathMl(writer, mathml);
    try writer.writeByte('\n');
    try writer.writeAll(
        \\    </div>
        \\  </foreignObject>
        \\</svg>
        \\
    );
}

fn writeNamespacedMathMl(writer: *std.Io.Writer, mathml: []const u8) std.Io.Writer.Error!void {
    const opening = "<math";
    std.debug.assert(std.mem.startsWith(u8, mathml, opening));
    try writer.writeAll("<math xmlns=\"http://www.w3.org/1998/Math/MathML\"");
    try writer.writeAll(mathml[opening.len..]);
}

fn fatal(init: std.process.Init, comptime format: []const u8, args: anytype) noreturn {
    var stderr_buffer: [1024]u8 = undefined;
    var stderr_writer = std.Io.File.stderr().writer(init.io, &stderr_buffer);
    stderr_writer.interface.print("generate-formula-logo: " ++ format ++ "\n", args) catch {};
    stderr_writer.interface.flush() catch {};
    std.process.exit(1);
}

test "strips optional inline delimiters" {
    try std.testing.expectEqualStrings("M^{\\,z}", stripInlineDelimiters(" $M^{\\,z}$ ").?);
    try std.testing.expectEqualStrings("M", stripInlineDelimiters("M").?);
    try std.testing.expect(stripInlineDelimiters("$$") == null);
}

test "accepts only six-digit hex colors" {
    try std.testing.expect(isHexColor("#2563eb"));
    try std.testing.expect(isHexColor("#F8FAFC"));
    try std.testing.expect(!isHexColor("2563eb"));
    try std.testing.expect(!isHexColor("#fff"));
    try std.testing.expect(!isHexColor("#12345g"));
}

test "embeds rendered MathML and colors in SVG" {
    var rendered = try math.renderMathMlAlloc(std.testing.allocator, "M^{\\,z}", .{});
    defer rendered.deinit(std.testing.allocator);
    const mathml = switch (rendered) {
        .output => |output| output,
        .diagnostic => return error.UnexpectedDiagnostic,
    };

    var output: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer output.deinit();
    try writeSvg(&output.writer, mathml, "#2563eb", "#f8fafc");

    try std.testing.expect(std.mem.indexOf(u8, output.written(), "fill=\"#2563eb\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.written(), "color:#f8fafc") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.written(), "<msup>") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.written(), "width=\"0.1667em\"") != null);
    try std.testing.expect(std.mem.indexOf(
        u8,
        output.written(),
        "<math xmlns=\"http://www.w3.org/1998/Math/MathML\"",
    ) != null);
}
